-- Country table
CREATE TABLE Country (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    population INTEGER,
    PRIMARY KEY (id)
);

-- Country covid data
CREATE TABLE Country_covid_data (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_date DATE NOT NULL,
    daily_tests INTEGER,
    daily_positive_cases INTEGER,
    daily_deaths INTEGER,
    daily_vaccinations INTEGER,
    country_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES Country(id)
);

-- State table
CREATE TABLE State (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    country_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES Country(id)
);

-- Vaccination data
CREATE TABLE Vaccination_data (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_date DATE NOT NULL,
    daily_first_doses INTEGER,
    daily_first_doses_12plus INTEGER,
    daily_first_doses_18plus INTEGER,
    daily_first_doses_65plus INTEGER,
    daily_fully_vaccinated INTEGER,
    daily_fully_vaccinated_12plus INTEGER,
    daily_fully_vaccinated_18plus INTEGER,
    daily_fully_vaccinated_65plus INTEGER,
    state_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id) REFERENCES State(id)
);

-- Hospitalization data
CREATE TABLE Hospitalization_data (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_date DATE NOT NULL,
    total_beds INTEGER,
    total_beds_coverage INTEGER,
    covid_occupied_beds INTEGER,
    covid_occupied_beds_coverage INTEGER,
    icu_beds INTEGER,
    icu_beds_coverage INTEGER,
    covid_occupied_icu_beds INTEGER,
    covid_occupied_icu_beds_coverage INTEGER,
    state_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id) REFERENCES State(id)
);

-- County table
CREATE TABLE County (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    population INTEGER,
    state_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id) REFERENCES State(id)
);

-- County covid data
CREATE TABLE County_covid_data (
    id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    record_date DATE NOT NULL,
    daily_positive_cases INTEGER,
    daily_deaths INTEGER,
    county_id INTEGER NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (county_id) REFERENCES County(id)
);

-- Indexes for faster query results
CREATE INDEX County_covid_data_index
ON County_covid_data(record_date);

CREATE INDEX County_index
ON County(state_id);